_target_: evaluation.dataset.cityscapes.CityscapesDataset
root: "${project_root}/data/cityscapes"
split: "train"
transform: null 
target_transform: null 
include_labels: True
num_classes: 19  
tag: "cityscapes" 